### ISSUE TITLE
Very nice idea, but how do I get the first coal that I can put into an ore mine?

### ISSUE THREAD

**Issue by erikbgithub** [msakuta/FactorishJS#1]
Hi, I really like the idea of that simplified version of the game and that I can easily play it in the browser.
However, I have a problem getting started.

If I click on the coal, it seems like nothing happens [1]. And I don't see a tool or machine that can get the coal for me [2].
Intuitively I would say the Ore Miner should be able to get coal, but it needs coal to work as well to start.

One tip, please!

![searching for next step to get coal](https://i.imgur.com/PmF9MUq.png)

**Comment by msakuta** [comment]
You have few ore mines at start. You can put them on the ores, click on the ore mine to open its inventory, and put coal ores in it to start mining.
This is the ore mine (yeah, I know it doesn't look like it :) )
![image](https://user-images.githubusercontent.com/2798715/122659324-ff71d980-d1b1-11eb-82bf-822b728596ea.png)

But I think it's good to have right click mining as Factorio does. I will think about it.

BTW, I have another similar project called [FactorishWasm](https://msakuta.github.io/FactorishWasm/index.html), which has a little bit more features. I'm more focused on FactorishWasm since it is more enjoyable to work with WebAssembly and Rust.

**Comment by msakuta** [comment]
I added mining ores with mouse right click. Also I added some documentation in [README.md](https://github.com/msakuta/FactorishJS/blob/master/README.md) since it was not clear how to open the inventory or how to play in general.

**Comment by erikbgithub** [comment]
Loving it! So for the user the WASM version is basically the same, just with a few more features, and for coding it's more fun. Well, then I check it out as well!

Right clicking works well, thanks for implementing it!
